### ISSUE TITLE
Stream connection lost: error(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by puneetbatra87** [wangyuhuiever/django-rabbitmq#2]
Now the consumer is started and I am getting the below mentioned error (Consumer starts consuming the records but after some time this happens): - 

Exception in thread mq_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/puneetbatra/billing_module/billing_services/django_rabbitmq/apps.py", line 29, in run_mq
    mq.start_mq(mq_settings.get('QUEUE'))
  File "/home/puneetbatra/billing_module/billing_services/django_rabbitmq/mq.py", line 20, in start_mq
    channel.start_consuming()
  File "/home/puneetbatra/billing_module/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home/puneetbatra/billing_module/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home/puneetbatra/billing_module/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/home/puneetbatra/billing_module/env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
    raise self._closed_result.value.error
StreamLostError: Stream connection lost: error(104, 'Connection reset by peer')

**Comment by wangyuhuiever** [comment]
can you get me a reproduce step?
my environment:
python 3.8
django 3.1.2
pika 1.1.0

I though this maybe a pika version error
